#!/usr/bin/env bash

# setting user for additional cron jobs
case $1 in
-u=*|--user=*)
    crontab_user="-u ${1#*=}"
    shift
    ;;
-u|--user)
    crontab_user="-u $2"
    shift 2
    ;;
-*)
    echo "Unknown option: ${1%=*}" > /dev/stderr
    exit 1
    ;;
*)
    crontab_user=""
    ;;
esac

# start cron
default_crontabs_dir=/etc/crontabs
crond -L /var/log/cron.log -c ${CRONTABS_DIR:-$default_crontabs_dir}

# trap SIGINT and SIGTERM signals and gracefully exit
trap "echo \"stopping cron\"; kill \$!; exit" SIGINT SIGTERM

# add heartbeat
crontab -l | { cat; echo "*/${LIVENESS_THRESHOLD:-1} * * * * heartbeat"; } | crontab -

# add crontabs
crontab -l | { cat; echo "${CRONTABS}"; } | crontab -

# start "daemon"
while true
do
    cat /var/log/cron.log & wait $!
done
