apiVersion: apps/v1
kind: Deployment
metadata:
  name: disk-check
spec:
  selector:
    matchLabels:
      app: disk-check-app
  replicas: 1
  template:
    metadata:
      labels:
        app: disk-check-app
    spec:
      volumes:
        - name: disk-check-script
          configMap:
            name: disk-check-script
      containers:
        - name: app
          image: s1s5/cron:alpine
          env:
            - name: TARGET_PATH
              value: "/"
            - name: THRESHOLD
              value: "80"
            - name: CRONTABS
              value: |
                * * * * * /bin/bash /opt/check-disk >> /var/lib/cron.log 2>&1
          livenessProbe:
            exec:
              command:
                - check-liveness
            initialDelaySeconds: 120
            periodSeconds: 60
          volumeMounts:
            - name: disk-check-script
              mountPath: /opt/
              readOnly: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: disk-check-script
data:
  check-disk: |
    if [ $((100 * `env stat -f -c %f ${TARGET_PATH}` / `env stat -f -c %b ${TARGET_PATH}`)) -lt ${THRESHOLD} ]; then
      echo ok > /tmp/out
    else
      echo ng > /tmp/out
    fi
